export { default as assets } from './assets'
export { default as game } from './game'
export { default as graphics } from './graphics'
export { default as input } from './input'
export { default as music } from './music'
export { default as sfx } from './sfx'
export { default as sprite } from './sprite'
