export default [
  { code: 8, label: 'backspace' },
  { code: 9, label: 'tab' },

  { code: 13, label: 'enter' },

  { code: 16, label: 'shift' },
  { code: 17, label: 'ctrl' },
  { code: 18, label: 'alt' },

  { code: 20, label: 'caps' },

  { code: 27, label: 'escape' },

  { code: 32, label: 'space' },
  { code: 33, label: 'pageUp' },
  { code: 34, label: 'pageDown' },
  { code: 35, label: 'end' },
  { code: 36, label: 'home' },
  { code: 37, label: 'left' },
  { code: 38, label: 'up' },
  { code: 39, label: 'right' },
  { code: 40, label: 'down' },

  { code: 45, label: 'insert' },
  { code: 46, label: 'delete' },

  { code: 48, label: 'zero' },
  { code: 49, label: 'one' },
  { code: 50, label: 'two' },
  { code: 51, label: 'three' },
  { code: 52, label: 'four' },
  { code: 53, label: 'five' },
  { code: 54, label: 'six' },
  { code: 55, label: 'seven' },
  { code: 56, label: 'eight' },
  { code: 57, label: 'nine' },

  { code: 65, label: 'A' },
  { code: 66, label: 'B' },
  { code: 67, label: 'C' },
  { code: 68, label: 'D' },
  { code: 69, label: 'E' },
  { code: 70, label: 'F' },
  { code: 71, label: 'G' },
  { code: 72, label: 'H' },
  { code: 73, label: 'I' },
  { code: 74, label: 'J' },
  { code: 75, label: 'K' },
  { code: 76, label: 'L' },
  { code: 77, label: 'M' },
  { code: 78, label: 'N' },
  { code: 79, label: 'O' },
  { code: 80, label: 'P' },
  { code: 81, label: 'Q' },
  { code: 82, label: 'R' },
  { code: 83, label: 'S' },
  { code: 84, label: 'T' },
  { code: 85, label: 'U' },
  { code: 86, label: 'V' },
  { code: 87, label: 'W' },
  { code: 88, label: 'X' },
  { code: 89, label: 'Y' },
  { code: 90, label: 'Z' }
]
